language: elixir
matrix:
  include:
    - elixir: 1.5.3
      otp_release: 20.3.8
    - elixir: 1.6.6
      otp_release: 21.0.4
    - elixir: 1.7.1
      otp_release: 21.0.4
script:
  - "MIX_ENV=test mix do deps.get, compile, test"
